name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      env:
        DB_HOST: 127.0.0.1
        DB_DATABASE: readcsv
        DB_PORT: '3306'
        DB_USERNAME: root
        DB_PASSWORD: Aad&8asdlf42@$
    - name: Copy to env file
      run : |
        echo DB_HOST=${{env.DB_HOST}} >> .env
        echo DB_DATABASE=${{env.DB_DATABASE}} >> .env
        echo DB_PORT=${{env.DB_PORT}} >> .env
        echo DB_USERNAME=${{env.DB_USERNAME}} >> .env
        echo DB_PASSWORD=${{env.DB_PASSWORD}} >> .env
        echo 'List all directories'
        echo ls -la



